#!/bin/bash -ue

./RunUnitTests

if
    [ $? = 0 ];
    then ./StartDocker;
    else
        exit 1;
fi

if  
    [ $? = 0 ];
    then ./RunIntegrationTests;
    else
        exit 1;
fi

if
    [ $? = 0 ];
    then exit 0;
    else
        exit 1;
fi